/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/branding/Styleguide_PM_V6_Page_01.webp';
import i1 from '@/public/images/branding/Styleguide_PM_V6_Page_04.webp';
import i2 from '@/public/images/branding/Styleguide_PM_V6_Page_07.webp';
import i3 from '@/public/images/branding/mw5-box-art.webp';
import i4 from '@/public/images/branding/sierra-wireless-ad.webp';
import i5 from '@/public/images/branding/smartt-ad.webp';
import i6 from '@/public/images/branding/smartt-folder-front.webp';
import i7 from '@/public/images/branding/smartt-folder.webp';
import i8 from '@/public/images/print/mechcon-2016-img1.webp';
import i9 from '@/public/images/print/mechcon-2016-img2.webp';
import i10 from '@/public/images/print/mechcon-2017-img1.webp';
import i11 from '@/public/images/print/mechcon-2017-img2.webp';
import i12 from '@/public/images/print/mechcon-2017-img3.webp';
import i13 from '@/public/images/print/mechcon-2017-img4.webp';
import i14 from '@/public/images/print/mechcon-2017-img5.webp';
import i15 from '@/public/images/print/mechcon-2017-img6.webp';
import i16 from '@/public/images/print/mechcon-2017-img7.webp';
import i17 from '@/public/images/print/mechcon-2017-img8.webp';
import i18 from '@/public/images/print/mechcon-2018-img1.webp';
import i19 from '@/public/images/print/mechcon-2018-img2.webp';
import i20 from '@/public/images/print/mechcon-2018-img3.webp';
import i21 from '@/public/images/print/mechcon-2018-img4.webp';
import i22 from '@/public/images/print/mechcon-2018-img5.webp';
import i23 from '@/public/images/print/mechcon-2018-img6.webp';
import i24 from '@/public/images/print/mechcon-2018-img7.webp';

const imageMap = {
  '/images/branding/Styleguide_PM_V6_Page_01.webp': i0,
  '/images/branding/Styleguide_PM_V6_Page_04.webp': i1,
  '/images/branding/Styleguide_PM_V6_Page_07.webp': i2,
  '/images/branding/mw5-box-art.webp': i3,
  '/images/branding/sierra-wireless-ad.webp': i4,
  '/images/branding/smartt-ad.webp': i5,
  '/images/branding/smartt-folder-front.webp': i6,
  '/images/branding/smartt-folder.webp': i7,
  '/images/print/mechcon-2016-img1.webp': i8,
  '/images/print/mechcon-2016-img2.webp': i9,
  '/images/print/mechcon-2017-img1.webp': i10,
  '/images/print/mechcon-2017-img2.webp': i11,
  '/images/print/mechcon-2017-img3.webp': i12,
  '/images/print/mechcon-2017-img4.webp': i13,
  '/images/print/mechcon-2017-img5.webp': i14,
  '/images/print/mechcon-2017-img6.webp': i15,
  '/images/print/mechcon-2017-img7.webp': i16,
  '/images/print/mechcon-2017-img8.webp': i17,
  '/images/print/mechcon-2018-img1.webp': i18,
  '/images/print/mechcon-2018-img2.webp': i19,
  '/images/print/mechcon-2018-img3.webp': i20,
  '/images/print/mechcon-2018-img4.webp': i21,
  '/images/print/mechcon-2018-img5.webp': i22,
  '/images/print/mechcon-2018-img6.webp': i23,
  '/images/print/mechcon-2018-img7.webp': i24,
};

export default imageMap;
