/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/animation/mechcon-logo-animation.webp';
import i1 from '@/public/images/animation/mw5-clans-teaser.webp';
import i2 from '@/public/images/animation/mwowc-tournament-logo.webp';
import i3 from '@/public/images/animation/piranha-games-bumper.webp';
import i4 from '@/public/images/animation/rise-of-rasalhague-trailer.webp';
import i5 from '@/public/images/animation/solaris-showdown-trailer.webp';
import i6 from '@/public/images/branding/Columbia_College_Brand_Guidelines_Final_Page_01.webp';
import i7 from '@/public/images/branding/GameManual_v2_5_Page_01.webp';
import i8 from '@/public/images/branding/Mechwarrior5-CLANS-game-manual-1.webp';
import i9 from '@/public/images/branding/Styleguide_PM_V6_Page_01.webp';
import i10 from '@/public/images/branding/mw5-box-art.webp';
import i11 from '@/public/images/branding/mw5-dev-tee.webp';
import i12 from '@/public/images/branding/sierra-wireless-ad.webp';
import i13 from '@/public/images/branding/technical-manual-2024-v01_Page_01.webp';
import i14 from '@/public/images/icons/mw5-clans-icon.webp';
import i15 from '@/public/images/icons/mw5-dlc2-icon.webp';
import i16 from '@/public/images/icons/mw5-dlc4-icon.webp';
import i17 from '@/public/images/icons/mw5-dlc5-icon.webp';
import i18 from '@/public/images/icons/mw5-dlc6-icon.webp';
import i19 from '@/public/images/icons/mw5-icon.webp';
import i20 from '@/public/images/icons/mwo-icon.webp';
import i21 from '@/public/images/icons/mwo/angel-800x800.png';
import i22 from '@/public/images/icons/smartt-icon.webp';
import i23 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-ibrahim.webp';
import i24 from '@/public/images/illustration/MW5C_TOW_KA_16x9.webp';
import i25 from '@/public/images/illustration/mw5mercs-tee-design.webp';
import i26 from '@/public/images/illustration/mwo-legends-art-atlas.webp';
import i27 from '@/public/images/illustration/vector-art-mw5-thumb.webp';
import i28 from '@/public/images/illustration/xmas-card-1.jpg';
import i29 from '@/public/images/illustration/xmas-card-2.webp';
import i30 from '@/public/images/logos/cc-logo-example.webp';
import i31 from '@/public/images/logos/ctd-logo-example.webp';
import i32 from '@/public/images/logos/hotis-logo-example.webp';
import i33 from '@/public/images/logos/kwc-logo-colour-example.webp';
import i34 from '@/public/images/logos/lotkl-logo-example.webp';
import i35 from '@/public/images/logos/mc-logo-example.webp';
import i36 from '@/public/images/logos/mw5-clans-logo-example.webp';
import i37 from '@/public/images/logos/mw5-logo-example.webp';
import i38 from '@/public/images/logos/mwol-logo-example.webp';
import i39 from '@/public/images/logos/pr-logo-example.webp';
import i40 from '@/public/images/logos/ror-logo-example.webp';
import i41 from '@/public/images/logos/smartt-logo-example.webp';
import i42 from '@/public/images/logos/ss-logo-example.webp';
import i43 from '@/public/images/logos/tdg-logo-example.webp';
import i44 from '@/public/images/logos/trypaud-colour-logo-example.webp';
import i45 from '@/public/images/print/mechcon-2018-img1.webp';
import i46 from '@/public/images/ui/ctd-img1.webp';
import i47 from '@/public/images/ui/hs-img1.webp';
import i48 from '@/public/images/ui/mechcon-homepage.webp';
import i49 from '@/public/images/ui/mw5-clans-homepage.webp';
import i50 from '@/public/images/ui/mw5-mercs-homepage.webp';
import i51 from '@/public/images/ui/mwo-product-page1.webp';
import i52 from '@/public/images/ui/mwomercs-legends-moonwalker.webp';
import i53 from '@/public/images/ui/pgi-homepage.webp';
import i54 from '@/public/images/ui/transverse-homepage.webp';

const imageMap = {
  '/images/animation/mechcon-logo-animation.webp': i0,
  '/images/animation/mw5-clans-teaser.webp': i1,
  '/images/animation/mwowc-tournament-logo.webp': i2,
  '/images/animation/piranha-games-bumper.webp': i3,
  '/images/animation/rise-of-rasalhague-trailer.webp': i4,
  '/images/animation/solaris-showdown-trailer.webp': i5,
  '/images/branding/Columbia_College_Brand_Guidelines_Final_Page_01.webp': i6,
  '/images/branding/GameManual_v2_5_Page_01.webp': i7,
  '/images/branding/Mechwarrior5-CLANS-game-manual-1.webp': i8,
  '/images/branding/Styleguide_PM_V6_Page_01.webp': i9,
  '/images/branding/mw5-box-art.webp': i10,
  '/images/branding/mw5-dev-tee.webp': i11,
  '/images/branding/sierra-wireless-ad.webp': i12,
  '/images/branding/technical-manual-2024-v01_Page_01.webp': i13,
  '/images/icons/mw5-clans-icon.webp': i14,
  '/images/icons/mw5-dlc2-icon.webp': i15,
  '/images/icons/mw5-dlc4-icon.webp': i16,
  '/images/icons/mw5-dlc5-icon.webp': i17,
  '/images/icons/mw5-dlc6-icon.webp': i18,
  '/images/icons/mw5-icon.webp': i19,
  '/images/icons/mwo-icon.webp': i20,
  '/images/icons/mwo/angel-800x800.png': i21,
  '/images/icons/smartt-icon.webp': i22,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-ibrahim.webp': i23,
  '/images/illustration/MW5C_TOW_KA_16x9.webp': i24,
  '/images/illustration/mw5mercs-tee-design.webp': i25,
  '/images/illustration/mwo-legends-art-atlas.webp': i26,
  '/images/illustration/vector-art-mw5-thumb.webp': i27,
  '/images/illustration/xmas-card-1.jpg': i28,
  '/images/illustration/xmas-card-2.webp': i29,
  '/images/logos/cc-logo-example.webp': i30,
  '/images/logos/ctd-logo-example.webp': i31,
  '/images/logos/hotis-logo-example.webp': i32,
  '/images/logos/kwc-logo-colour-example.webp': i33,
  '/images/logos/lotkl-logo-example.webp': i34,
  '/images/logos/mc-logo-example.webp': i35,
  '/images/logos/mw5-clans-logo-example.webp': i36,
  '/images/logos/mw5-logo-example.webp': i37,
  '/images/logos/mwol-logo-example.webp': i38,
  '/images/logos/pr-logo-example.webp': i39,
  '/images/logos/ror-logo-example.webp': i40,
  '/images/logos/smartt-logo-example.webp': i41,
  '/images/logos/ss-logo-example.webp': i42,
  '/images/logos/tdg-logo-example.webp': i43,
  '/images/logos/trypaud-colour-logo-example.webp': i44,
  '/images/print/mechcon-2018-img1.webp': i45,
  '/images/ui/ctd-img1.webp': i46,
  '/images/ui/hs-img1.webp': i47,
  '/images/ui/mechcon-homepage.webp': i48,
  '/images/ui/mw5-clans-homepage.webp': i49,
  '/images/ui/mw5-mercs-homepage.webp': i50,
  '/images/ui/mwo-product-page1.webp': i51,
  '/images/ui/mwomercs-legends-moonwalker.webp': i52,
  '/images/ui/pgi-homepage.webp': i53,
  '/images/ui/transverse-homepage.webp': i54,
};

export default imageMap;
