/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/icons/mw5-clans-icon.webp';
import i1 from '@/public/images/icons/mw5-dlc2-icon.webp';
import i2 from '@/public/images/icons/mw5-dlc4-icon.webp';
import i3 from '@/public/images/icons/mw5-dlc5-icon.webp';
import i4 from '@/public/images/icons/mw5-dlc6-icon.webp';
import i5 from '@/public/images/icons/mw5-icon.webp';
import i6 from '@/public/images/icons/mwo-icon.webp';
import i7 from '@/public/images/icons/smartt-icon.webp';

const imageMap = {
  '/images/icons/mw5-clans-icon.webp': i0,
  '/images/icons/mw5-dlc2-icon.webp': i1,
  '/images/icons/mw5-dlc4-icon.webp': i2,
  '/images/icons/mw5-dlc5-icon.webp': i3,
  '/images/icons/mw5-dlc6-icon.webp': i4,
  '/images/icons/mw5-icon.webp': i5,
  '/images/icons/mwo-icon.webp': i6,
  '/images/icons/smartt-icon.webp': i7,
};

export default imageMap;
