/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-ibrahim.webp';
import i1 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-leo-only.webp';
import i2 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-mia-only.webp';
import i3 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-ibrahim.webp';
import i4 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-leo-only.webp';
import i5 from '@/public/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-mia-only.webp';
import i6 from '@/public/images/illustration/MW5C_TOW_KA_16x9.jpg';
import i7 from '@/public/images/illustration/mw5mercs-tee-design.webp';
import i8 from '@/public/images/illustration/mwo-legends-art-atlas.webp';
import i9 from '@/public/images/illustration/xmas-card-1.webp';
import i10 from '@/public/images/illustration/xmas-card-2.webp';

const imageMap = {
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-ibrahim.webp': i0,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-leo-only.webp': i1,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-edit-mia-only.webp': i2,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-ibrahim.webp': i3,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-leo-only.webp': i4,
  '/images/illustration/MW5C_KA_16x9_v02_240717_Profile-noedit-mia-only.webp': i5,
  '/images/illustration/MW5C_TOW_KA_16x9.jpg': i6,
  '/images/illustration/mw5mercs-tee-design.webp': i7,
  '/images/illustration/mwo-legends-art-atlas.webp': i8,
  '/images/illustration/xmas-card-1.webp': i9,
  '/images/illustration/xmas-card-2.webp': i10,
};

export default imageMap;
