/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/logos/cc-logo-example.webp';
import i1 from '@/public/images/logos/ctd-logo-example.webp';
import i2 from '@/public/images/logos/hotis-logo-example.webp';
import i3 from '@/public/images/logos/mc-logo-example.webp';
import i4 from '@/public/images/logos/pr-logo-example.webp';
import i5 from '@/public/images/logos/smartt-logo-example.webp';

const imageMap = {
  '/images/logos/cc-logo-example.webp': i0,
  '/images/logos/ctd-logo-example.webp': i1,
  '/images/logos/hotis-logo-example.webp': i2,
  '/images/logos/mc-logo-example.webp': i3,
  '/images/logos/pr-logo-example.webp': i4,
  '/images/logos/smartt-logo-example.webp': i5,
};

export default imageMap;
