/* GENERATED by scripts/gen-image-imports.js — do not edit. */
/* eslint-disable */
import i0 from '@/public/images/ui/bb-img1.webp';
import i1 from '@/public/images/ui/bb-img2.webp';
import i2 from '@/public/images/ui/ctd-img1.webp';
import i3 from '@/public/images/ui/ctd-img2.webp';
import i4 from '@/public/images/ui/hs-img1.webp';
import i5 from '@/public/images/ui/hs-img2.webp';
import i6 from '@/public/images/ui/mechcon-about.webp';
import i7 from '@/public/images/ui/mechcon-homepage.webp';
import i8 from '@/public/images/ui/mechcon-tickets.webp';
import i9 from '@/public/images/ui/mw5-clans-dlc.webp';
import i10 from '@/public/images/ui/mw5-clans-homepage.webp';
import i11 from '@/public/images/ui/mw5-clans-news.webp';
import i12 from '@/public/images/ui/mw5-clans-purchase.webp';
import i13 from '@/public/images/ui/mw5-mercs-dlc1.webp';
import i14 from '@/public/images/ui/mw5-mercs-dlc2.webp';
import i15 from '@/public/images/ui/mw5-mercs-homepage.webp';
import i16 from '@/public/images/ui/mw5-mercs-media.webp';
import i17 from '@/public/images/ui/mwo-product-page1.webp';
import i18 from '@/public/images/ui/mwo-product-page2.webp';
import i19 from '@/public/images/ui/mwo-product-page3.webp';
import i20 from '@/public/images/ui/mwo-product-page4.webp';
import i21 from '@/public/images/ui/mwo-product-page5.webp';
import i22 from '@/public/images/ui/mwo-product-page6.webp';
import i23 from '@/public/images/ui/mwo-product-page7.webp';
import i24 from '@/public/images/ui/mwomercs-legends-moonwalker.webp';
import i25 from '@/public/images/ui/mwomercs-legends-moonwalker2.webp';
import i26 from '@/public/images/ui/pgi-careers.webp';
import i27 from '@/public/images/ui/pgi-homepage.webp';
import i28 from '@/public/images/ui/pgi-studio.webp';
import i29 from '@/public/images/ui/transverse-about.webp';
import i30 from '@/public/images/ui/transverse-checkout.webp';
import i31 from '@/public/images/ui/transverse-homepage.webp';
import i32 from '@/public/images/ui/transverse-product.webp';
import i33 from '@/public/images/ui/transverse-social.webp';

const imageMap = {
  '/images/ui/bb-img1.webp': i0,
  '/images/ui/bb-img2.webp': i1,
  '/images/ui/ctd-img1.webp': i2,
  '/images/ui/ctd-img2.webp': i3,
  '/images/ui/hs-img1.webp': i4,
  '/images/ui/hs-img2.webp': i5,
  '/images/ui/mechcon-about.webp': i6,
  '/images/ui/mechcon-homepage.webp': i7,
  '/images/ui/mechcon-tickets.webp': i8,
  '/images/ui/mw5-clans-dlc.webp': i9,
  '/images/ui/mw5-clans-homepage.webp': i10,
  '/images/ui/mw5-clans-news.webp': i11,
  '/images/ui/mw5-clans-purchase.webp': i12,
  '/images/ui/mw5-mercs-dlc1.webp': i13,
  '/images/ui/mw5-mercs-dlc2.webp': i14,
  '/images/ui/mw5-mercs-homepage.webp': i15,
  '/images/ui/mw5-mercs-media.webp': i16,
  '/images/ui/mwo-product-page1.webp': i17,
  '/images/ui/mwo-product-page2.webp': i18,
  '/images/ui/mwo-product-page3.webp': i19,
  '/images/ui/mwo-product-page4.webp': i20,
  '/images/ui/mwo-product-page5.webp': i21,
  '/images/ui/mwo-product-page6.webp': i22,
  '/images/ui/mwo-product-page7.webp': i23,
  '/images/ui/mwomercs-legends-moonwalker.webp': i24,
  '/images/ui/mwomercs-legends-moonwalker2.webp': i25,
  '/images/ui/pgi-careers.webp': i26,
  '/images/ui/pgi-homepage.webp': i27,
  '/images/ui/pgi-studio.webp': i28,
  '/images/ui/transverse-about.webp': i29,
  '/images/ui/transverse-checkout.webp': i30,
  '/images/ui/transverse-homepage.webp': i31,
  '/images/ui/transverse-product.webp': i32,
  '/images/ui/transverse-social.webp': i33,
};

export default imageMap;
