import Head from 'next/head';
import utilStyles from '../styles/utils.module.css';
import Layout, { siteTitle } from '../components/layout';
import Image from 'next/image';

export default function Logos({ allPostsData }) {
  return (
    <Layout home>
     <Head>
        <title>{siteTitle}</title>
      </Head>
      <section className={utilStyles.headingMd}>
      <div className={utilStyles.blog}>
        <h1>My Story</h1>
        <h3>Influences</h3>
        <p>The two biggest influences on my early life have been my mom and dad. They’ve helped me allot. I’ve been fortunate to get two good ones. My dad taught me how to work hard. My mom taught me how to be a good person. A strength and kindness skill set.</p>
        <p>Design is challenging. Life is challenging. There are parallels. In life it’s common to be rewarded for fitting in. Group assimilation. Design is the same. The cookie cutter design phenomena inspired a can you make it like they did attitude. Even with AI and it’s its new-found power within design, it still can’t trump human consciousness, there is a repetitiveness to it. Individual thought played out in the realm of collaboration is where innovation comes from. As a designer my individuality has allowed me to develop an imagination for creative problem solving. I don’t think like anyone else. And nor should you. This is my ace card. AI still can’t imagine. </p>
        <p>In the comedy of Bill Hicks, I discovered a kindred spirit. I think Rant in E-Minor is a work of art up there with da Vinci’s Mona Lisa or Mozart’s 5th Concerto. I honestly feel if he was still around we’d be friends. A conceit of mine I’ll admit. He’d be like “hey man I came up with a new bit…” and I’d be like “lay it on me Bill I’ll give you feedback.” I consider Bill a prophet, speaking in the prophetic tradition of oppression albeit through comedy rather than hymned platformed oratories akin to Martin Luther King. The stage was his pulpit. Like other prophets he was never fully appreciated during his time. In fact, his following only grew stronger after he passed inspiring many comics to take up the mantle of truth telling through stand-up.</p>
        <p>Bill is a hero to me. I consider his words nothing less than profound. His act was iconoclastic. He was a designer of hilarity sent back in time by the Universe to help the species evolve, a bit like the terminator but with jokes. I’ve done stand-up. It’s difficult. I bombed allot. But coming from Northern Ireland that shouldn’t be a surprise ba-dum-bum. 
      </p>
        <p>To the best of my knowledge Bill wasn’t a designer, yet his comedy was a constant in the iterative process. He could create new material at the drop of a hat, but what’s impressive was his constant tweaking of jokes that already worked over time. Themes, structure, timing, words, everything was subject to change or more precisely improvement. By observing his comedy over the span of his career, from when he first went on stage at the tender age of 15 to his final show when he was dying of pancreatic cancer, you could, potentially say if Bill was a designer, a tenant might be: if something worked could it work better? If true update. Cue more laughter.</p>
        <p>Since a kid I’ve always been fascinated with the subject of UFOs. Bill spoke about this topic profusely in his act. One of the great things about Bill’s comedy which sets him apart even from the other great comedic teachers, George Carlin, Lenny Bruce, Richard Pryor, was his ability to educate you about things you didn’t already know.</p>
        <p>His act was inspirational and a learning experience. For example: consuming psilocybin magic mushrooms and UFO’s appearing was something I garnered from his work. I put this into practice many years later when I moved to Vancouver. Inspired by Hicks myself and 3 friends went on a camping trip off the coast of British Colombia. After consuming some psilocybin, an amount the philosopher Terrence McKenna calls a heroic dose, to our astonishment we witnessed dozens of lights switch on like light bulbs from the cloudless blue sky of a warm July evening over the open water that felt overwhelmingly otherworldly. The brightest of which appeared to communicate ideas telepathically about the nature of reality. This experience was transformative for the 4 of us. It has singlehandedly fueled my outlook on what’s creatively possible. AI still can’t take hallucinogenics. A major plus for humanity. As Bill himself use to say “What’s real, what’s imagined and what’s the difference.” Whatever it is you still need design to communicate it.</p>
        <h3>Creativity & Discipline</h3>
        <p>Life can be full of negative experiences. Being bullied taught me two things: you need to stand up for yourself and you need to need to develop a strong personality on the inside. To achieve this I meditate, practice breathwork, take cold showers, exercise, read (mostly non-fiction) and try to do something creative almost every day. When working with others it’s important to realise the stress and trauma of existence in which we all operate. In professional working relationships you need to develop a respectful attitude that has forgiveness at its base. No one’s perfect and sometimes we can be motivated by selfish actions which ultimately leave us unfulfilled. It’s important to try to trust the people we work with and communicate honestly. The hope is this inspires successful collaborative relationships so; creativity can blossom.</p>
        <p>Design is an emotional endeavour. Controlling your ego is an important aspect. This requires self-discipline. It prevents design critique from feeling too personal. Practicing martial arts from a young age instilled in me the courage to overcome allot of psychological barriers. Competing in Martial Arts tournaments taught me how to dig deep and keep pushing even when I’m losing. I’ve often felt like this at certain points in a design project. You’ve got to keep going. Even when you can’t see the light at the end of the tunnel. You might have to pull an all-nighter. Things usually come together in the end. Performing stand-up comedy taught me trying to make a room full of stranger’s laugh with your own material is the toughest fight you can have; at least when you first start performing. Not everyone is Hicks. Yet the obstacle is always the same, you and that nagging feeling of being judged.</p>
        <p>As a Designer you do need a healthy amount of ego. If you lack confidence in what you’re doing the chances you create something exceptional are small. If the team your collaborating with are emotionally absent in the process, the lower the probability you create something innovative. Once you expose yourself through a piece of creativity it will be analysed: sometimes harshly. Through repeated design fails my skin got thicker.</p>
        <h3>My Creative Process</h3>
        <p>I believe innovation within a brief should always be the goal. As the saying goes there are many ways to skin a feline. From building websites to designing logos many paths exist to achieve a result. I prefer a flexible approach to a design process with an ability to add complexity when needed. An agreed upon structure between team members, a client, CEO or project manager, prior to a project commencing is best practice.
          </p>
          <p>I usually start off my sketching. It starts the mind thinking before you pick up any design tools. This is true for websites, apps, logo design, even game development. The end result will ultimately have degrees of difference, but you can stumble upon a kernel of truth to expand upon with further exploration. It allows for rapid prototyping without the heavy lifting of code. You can make the wrong assumptions and test them out quickly. Checking with a team member or client to see if your napkin sketch is on the right path avoids early fatal consequences.</p>
          <p>Depending on project complexity getting to an early prototype on anything should always be the goal. You can’t begin sculpting without any clay. Yet the start isn’t where you will end up. It’s important not to get attached to things. Like a long mock-up phase in building a site or app, making it look pretty without experimenting with interactive elements or adding real data. You can spend significant investment in a logo concept created in Illustrator, adding color tweaking vector points, only for it to be rejected as soon as you show it to the client. The design process involves taking away things you don’t need anymore. Good design is usually less. Great design places the user at the center of the process.</p>
          <p>For the final incarnation of anything following mathematical principles is paramount. You can have your pi and eat it when used correctly. The use of grids in design has long been established and something I endorse. They can be simple. Designs should have a mathematical structure. You can use line height and word length of the typography you’ve chosen to build a layout grid or rely on the mathematical beauty of the Fibonacci sequence, the golden ratio or the rule of thirds. Using squared numbers for icon size. Dove tailing with current resolution sizes for screens and laptops. Connecting things with organised numbers allows for your design to scale up and down which is a necessity for the integrity of a visual flow.</p>
          <p>AI has a place in the creative process.</p>
        </div>
        </section>
        <a href="/">&larr; home</a>
      </Layout>
    );
}

