import Head from 'next/head';
import utilStyles from '../styles/utils.module.css';
import Layout, { siteTitle } from '../components/layout';
import Image from 'next/image';

export default function Logos({ allPostsData }) {
  return (
    <Layout home>
     <Head>
        <title>{siteTitle}</title>
      </Head>
      <section className={utilStyles.headingMd}>
      <div className={utilStyles.blog}>
        <h1>My Story</h1>
        <p>I’ve always been a designer at heart. As a kid I found drawing and painting easy which is why I made a commitment to focus on computing at an early point in school. </p>
        <Image className={utilStyles.contentImg} src="/images/portfolio-pic.jpg" width={960} height={540} alt="solaris showdown"/>
        <p>The internet was just taking off and I could see how combining creativity with technical acumen would provide a collaborative relationship with these disciplines beneficial to me later in life. This motivated me to pursue a bachelor’s course ‘Interactive Multimedia Design’ at the University of Ulster in the North of Ireland. Having graduated and still indecisive about what to do for employment I felt becoming more enlightened in this subject would increase by job prospects. I felt studying ‘Computing and Design’ for a Master’s Degree would achieve this objective. The course offered more detailed theory on more complex aspects of computing such as Networks and Programming as well as supplementing by design skills with additional design focused modules on Typography and User Interfaces. Upon graduation I gained employment in the South of Ireland as a junior UI designer with a small but growing software development company aptly named Screendragon specialising in Marketing Software for Global Agencies. I gained great experience working under the art director in tandem with developers, project managers and UX advocates. Delivering projects for many established companies such as Kimberley Clark and P&G.</p>
        <p>My education has evolved since University. I’m a lifelong believer in self learning. I’m constantly expanding upon my capabilities through reading and experimentation. I devour design books. Insights from other designers whom I would never get a chance to work with has proved invaluable to my growth. It was this learning itch which drove my ambition to leave Ireland and take a chance in a job market in another part of the world. This led me to the sunny shores of Vancouver British Columbia.</p>
        <Image className={utilStyles.contentImg} src="/images/books.jpg" width={960} height={540} alt="solaris showdown"/>
        <p>I arrived in Vancouver in November 2010 during a cold wet night. There would be many. Exactly like Ireland I thought. My friend picked me up at the airport and assured me the sun would emerge at the tail end of spring. As soon as I sorted out accommodation, someone’s couch, I busied myself with applications for UI design jobs. This had been my focus at Screendragon in Ireland. However, I soon realised my core technical skills, in essence working with Macromedia Flash, or should I say Adobe Flash and predominantly coding in Action Script were not what a vast array of businesses desired. Steve Jobs had killed flash or so the story goes. I had a solid foundation in HTML and CSS but never applied them at the same scale in a professional development environment. I had good skills in Photoshop and Illustrator which would always overlap with most design gigs.  Over the next 8 weeks I set about improving my knowledge base with online tutorials in order to bridge the gap.</p>
        <p>I was fortuitous enough to catch a break with a job offer before the start of the New Year with Smartt, a marketing consultancy in Burnaby. This saved my bacon as I was running low on personal funds and all the personal privacy a couch provides. Even though they felt my Front End Development experience was limited they took a chance due to my ambition for self-improvement, portfolio and solid references from my last employer. I was now in North America working as a Graphic and Web Designer.</p>
        <p>I was immediately in the thick of things working on an incubator project named Connect The Doc, an online booking system for medical clinics. I lead the design of the Front-End code base, guiding the clients through wireframes, mock-ups for the user side and client side of the site as well as updating the branding for the overall look and feel. I gained an immense amount of experience working at Smartt especially when it came to time management and project organisation. It was a diverse role. I learned about holistic brand storytelling and knowledge of Google Analytics to update the design of websites for a better user experience. I spearheaded the internal rebranding project for the company to better reflect the array of services they offered. Pursuant to this was a branding project for Columbia College to give it a competitive edge for attracting new students as well as contributing to the design of the accompanying website. I left Smartt a more complete designer ready for a new challenge.</p>
        <p>My next stop was Piranha Games, a game development company developing titles for the Mechwarrior Franchise. I signed up as the Interactive Designer and have spent ten years at the company. I’ve lead design projects for the web, worked on the UI for Mechwarrior Online, designed assets for the games, worked on branding for live game events and digital marketing campaigns. It’s been the culmination of allot of hard work and a chance to design for a popular game franchise with a committed fan base. It’s given me the chance to work with a diverse team of developers, marketers, game designers, art directors and a passionate CEO. The position has given me allot of growth. I can honestly say I wouldn’t be the designer I am today without Mechwarrior.</p>
        <p>At Piranha I’ve pushed my logo development skills creating different typographic treatments from the ground up rather than relying on pre-existing typefaces. I’ve explored best practices for web development and realised the value of being able to create bespoke design solutions in the browser for rapid development. Timelines can vary from months to days. You have to choose the right approach on a project by project basis. My frontend coding skills evolved in unison with my graphic art skills. The branding and web design for MW5 has been a particular pleasure: shipping a game is no easy task. The company is set to launch another standalone game this year in the form of Mechwarrior 5: Clans. After a successful logo development phase, we’re in the middle of planning for the product website. Look out for it in 2024.</p>
        </div>
        </section>
        <a href="/">&larr; home</a>
      </Layout>
    );
}

