import Head from 'next/head';
import utilStyles from '../styles/utils.module.css';
import Layout, { siteTitle } from '../components/layout';
import Image from 'next/image';

export default function Logos({ allPostsData }) {
  return (
    <Layout home>
     <Head>
        <title>{siteTitle}</title>
      </Head>
      <section className={utilStyles.headingMd}>
      <div className={utilStyles.blog}>
        <h1>My Story</h1>
       <p>I’ve always been a designer at heart. As a kid the components of art, drawing and painting, came naturally to me which is why I made a commitment to focus on translating these faculties, through computing, at an early point in my education. </p>
        <Image className={utilStyles.contentImg} src="/images/portfolio-pic.jpg" width={960} height={540} alt="solaris showdown"/>
        <p>The internet was just taking off and I could see how combining creativity with technical acumen could provide a collaborative relationship for these disciplines in the form of a career. This motivated me to pursue a bachelor’s course ‘Interactive Multimedia Design’ at the University of Ulster in the North of Ireland. Having graduated and undecided about what to do for employment I felt becoming more enlightened in this subject would increase by job prospects. I looked for further learning from the University of Ulster and stumbled upon ‘Computing and Design’ for a Master’s Degree, hoping to achieve this objective. The course offered more detailed theory on more complex aspects of computing such as Networks and Programming as well as supplementing by design skills with additional design focused modules on Typography, 3D Modelling, Animation and UI Design. Upon graduation I gained employment in the South of Ireland as a junior designer with a small but growing software development company aptly named Screendragon, developing Marketing Software for Global Agencies. I gained great experience working under the art director in tandem with developers, project managers and UX advocates. Delivering projects for many established companies such as Kimberley Clark and P&G.</p>
        <p> I’m a lifelong believer in self learning. My knowledge base has evolved since University.  I’m constantly expanding upon my abilities through reading and experimentation. I love design books. Insights from other designers whom I would never get a chance to work with has proved invaluable to my growth. It was this learning itch which drove my ambition to leave Ireland and take a chance in a job market in another part of the world. This led me to the sunny shores of Vancouver British Columbia.</p>
        <Image className={utilStyles.contentImg} src="/images/books.jpg" width={960} height={540} alt="solaris showdown"/>
        <p>I arrived in Vancouver in November 2010 during a cold wet night. There would be many. Exactly like Ireland I thought. My friend picked me up at the airport and assured me the sun would emerge at the tail end of spring. As soon as I sorted out accommodation, someone’s couch, I busied myself with applications for UI design jobs. This had been my focus at Screendragon in Ireland. However, I soon realized my core technical skills, in essence working with Adobe Flash, formerly Macromedia and predominantly coding in Action Script were not what a vast array of businesses desired. Flash was becoming less ubiquitous on the web with the vanguard of HTML 5 offering comparable functionality. I had a solid foundation in HTML and CSS but never applied them at the same scale in a professional development environment. My design chops in Photoshop and Illustrator were solid, usually desired with most design gigs.  Over the next 8 weeks I set about upgrading my CSS/ HTML skills with a focus on HTML5/ CSS 3 via tutorials and books, to bridge the knowledge gap.</p>
        <p>I was fortuitous enough to catch a break with a job offer before the start of the New Year with Smartt, a marketing consultancy in Burnaby. This saved my bacon as I was running low on money and privacy, putting up with all the personal privacy a couch provides while drunk Irish lads stumble home in the early hours. Even though they felt my Development experience was limited to Flash, they took a chance due to my ambition for self-improvement, portfolio and solid references from my last employer. I was now in North America working as a Graphic and Web Designer.</p>
        <p>I was immediately in the thick of things working on an incubator project named Connect The Doc, an online booking system for medical clinics. I lead the design of the Front-End code base, guiding the clients through wireframes, mock-ups for the user side and client side of the site as well as updating the branding for the overall look and feel. I gained an immense amount of experience working at Smartt especially when it came to time management and project organization. It was a diverse role. I learned about holistic brand storytelling and knowledge of Google Analytics to update the design of sites for a better user experience. I spearheaded the internal rebranding project for the company to better reflect their new positioning as a marketing consultancy. Pursuant to this was a branding project for Columbia College to give it a competitive edge for attracting new students as well as contributing to the design of the accompanying website. I left Smartt a more complete designer ready for a new challenge.</p>
        <p>My next stop was Piranha Games, a game development company creating titles for the Mechwarrior Franchise. I signed up as the Interactive Designer and have spent ten years at the company. I’ve lead design projects for the web, worked on the UI for Mechwarrior Online, designed assets for the games, worked on branding for live game events and digital marketing campaigns. It’s been the culmination of allot of hard work and a chance to design for a popular game franchise with a committed fan base. It’s given me the chance to work with a diverse team of developers, marketers, game designers, creative directors, art directors and a passionate CEO. The position has supplemented my growth as a well-rounded designer. I can honestly say I wouldn’t be the designer I am today without the freedom the Mechwarrior brand has provided.</p>
        <p>At Piranha I’ve pushed my logo development skills creating bespoke typographic treatments from the ground up. I’ve explored best practices for web development and realized the value of being able to create UI design solutions in the browser for rapid development. Timelines can vary from months to days. You have to choose the right approach on a project by project basis. My frontend coding skills evolved in unison with my graphic art skills. The branding and web design for MW5 has been a particular pleasure: shipping a game is no easy task. The company is set to launch another standalone game this year in the form of Mechwarrior 5: Clans. After a successful branding phase, and initial marketing push with hype trailers, we’re now in the middle of planning for the product website. Look out for it in 2024.</p>

        </div>
        </section>
        <a href="/">&larr; home</a>
      </Layout>
    );
}

